
[     UTC     ] Logs for aureliusjustin-jotform-result-app-bhxuss.streamlit.app/
────────────────────────────────────────────────────────────────────────────────────────
[08:20:55] 🖥 Provisioning machine...
[08:20:55] 🎛 Preparing system...
[08:20:55] ⛓ Spinning up manager process...
[08:18:33] 🚀 Starting up repository: 'jotform-result', branch: 'main', main module: 'app.py'
[08:18:33] 🐙 Cloning repository...
[08:18:34] 🐙 Cloning into '/mount/src/jotform-result'...

[08:18:34] 🐙 Cloned repository!
[08:18:34] 🐙 Pulling code changes from Github...
[08:18:34] 📦 Processing dependencies...

──────────────────────────────────────── uv ───────────────────────────────────────────

Using uv pip install.
Using Python 3.13.5 environment at /home/adminuser/venv
  × No solution found when resolving dependencies:
  ╰─▶ Because only the following versions of numpy are available:
          numpy<=1.26.0
          numpy==1.26.1
          numpy==1.26.2
          numpy==1.26.3
          numpy==1.26.4
          numpy>2
      and pandas==2.1.3 depends on numpy>=1.26.0,<2, we can conclude that
      pandas==2.1.3 depends on numpy>=1.26.0,<=1.26.4.
      And because you require pandas==2.1.3 and numpy==1.24.3, we can conclude
      that your requirements are unsatisfiable.
Checking if Streamlit is installed
Installing rich for an improved exception logging
Using uv pip install.
Using Python 3.13.5 environment at /home/adminuser/venv[2025-07-09 08:18:35.620409] 
Resolved 4 packages in 110ms
Prepared 4 packages in 129ms
Installed 4 packages in 17ms
 + markdown-it-py==[2025-07-09 08:18:35.881082] 3.0.0
 + mdurl==0.1.2
 + pygments==2.19.2
 + rich==14.0.0

────────────────────────────────────────────────────────────────────────────────────────


──────────────────────────────────────── pip ───────────────────────────────────────────

Using standard pip install.
Collecting streamlit==1.28.1 (from -r /mount/src/jotform-result/requirements.txt (line 1))
  Downloading streamlit-1.28.1-py2.py3-none-any.whl.metadata (8.1 kB)
Collecting pandas==2.1.3 (from -r /mount/src/jotform-result/requirements.txt (line 2))
  Downloading pandas-2.1.3.tar.gz (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 60.1 MB/s eta 0:00:00[2025-07-09 08:18:37.942351] 
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [87 lines of output]
      + meson setup /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/.mesonpy-z2pn10xb/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=/tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/.mesonpy-z2pn10xb/build/meson-python-native-file.ini
      The Meson build system
      Version: 1.2.1
      Source dir: /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b
      Build dir: /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/.mesonpy-z2pn10xb/build
      Build type: native build
      Project name: pandas
      Project version: 2.1.3
      C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
      C linker for the host machine: cc ld.bfd 2.35.2
      C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
      C++ linker for the host machine: c++ ld.bfd 2.35.2
      Cython compiler for the host machine: cython (cython 0.29.37)
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python found: YES (/home/adminuser/venv/bin/python)
      Did not find pkg-config by name 'pkg-config'
      Found Pkg-config: NO
      Run-time dependency python found: YES 3.13
      Build targets in project: 53
      
      pandas 2.1.3
      
        User defined options
          Native files: /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/.mesonpy-z2pn10xb/build/meson-python-native-file.ini
          buildtype   : release
          vsenv       : True
          b_ndebug    : if-release
          b_vscrt     : md
      
      Found ninja-1.11.1.git.kitware.jobserver-1 at /tmp/pip-build-env-br_29s3q/normal/bin/ninja
      
      Visual Studio environment is needed to run Ninja. It is recommended to use Meson wrapper:
      /tmp/pip-build-env-br_29s3q/overlay/bin/meson compile -C .
      + /tmp/pip-build-env-br_29s3q/normal/bin/ninja
      [1/151] Generating pandas/_libs/algos_take_helper_pxi with a custom command
      [2/151] Generating pandas/_libs/index_class_helper_pxi with a custom command
      [3/151] Generating pandas/_libs/hashtable_func_helper_pxi with a custom command
      [4/151] Generating pandas/_libs/khash_primitive_helper_pxi with a custom command
      [5/151] Generating pandas/_libs/algos_common_helper_pxi with a custom command
      [6/151] Generating pandas/_libs/hashtable_class_helper_pxi with a custom command
      [7/151] Generating pandas/_libs/sparse_op_helper_pxi with a custom command
      [8/151] Generating pandas/_libs/intervaltree_helper_pxi with a custom command
      [9/151] Generating pandas/__init__.py with a custom command
      [10/151] Compiling C object pandas/_libs/tslibs/parsing.cpython-313-x86_64-linux-gnu.so.p/.._src_parser_tokenizer.c.o
      [11/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/base.pyx
      [12/151] Compiling C object pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o
      FAILED: pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o
      cc -Ipandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p -Ipandas/_libs/tslibs -I../../pandas/_libs/tslibs -I../../../../pip-build-env-br_29s3q/overlay/lib/python3.13/site-packages/numpy/core/include -I../../pandas/_libs/include -I/usr/local/include/python3.13 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -w -std=c99 -O3 -DNPY_NO_DEPRECATED_API=0 -DNPY_TARGET_VERSION=NPY_1_21_API_VERSION -fPIC -MD -MQ pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o -MF pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o.d -o pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o -c pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c
      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c: In function ‘__Pyx_PyInt_As_long’:
      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:5397:27: error: too few arguments to function ‘_PyLong_AsByteArray’
       5397 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      In file included from /usr/local/include/python3.13/longobject.h:107,
                       from /usr/local/include/python3.13/Python.h:81,
                       from pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:6:
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c: In function ‘__Pyx_PyInt_As_int’:
      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:5631:27: error: too few arguments to function ‘_PyLong_AsByteArray’
       5631 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      In file included from /usr/local/include/python3.13/longobject.h:107,
                       from /usr/local/include/python3.13/Python.h:81,
                       from pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:6:
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      [13/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/dtypes.pyx
      [14/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/np_datetime.pyx
      [15/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/ccalendar.pyx
      [16/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/nattype.pyx
      [17/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/arrays.pyx
      [18/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/conversion.pyx
      [19/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/fields.pyx
      [20/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/strptime.pyx
      [21/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/parsing.pyx
      [22/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/offsets.pyx
      [23/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/timezones.pyx
      [24/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/vectorized.pyx
      [25/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/tzconversion.pyx
      [26/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/timestamps.pyx
      [27/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/timedeltas.pyx
      [28/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/tslibs/period.pyx
      [29/151] Compiling Cython source /tmp/pip-install-ulq5i5oc/pandas_9131e9f5175e44e5950b76a159c05f9b/pandas/_libs/algos.pyx
      ninja: build stopped: subcommand failed.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
Checking if Streamlit is installed
Installing rich for an improved exception logging
Using standard pip install.
Collecting rich>=10.14.0
  Downloading rich-14.0.0-py3-none-any.whl.metadata (18 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=10.14.0)
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.14.0)
  Downloading pygments-2.19.2-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.14.0)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading rich-14.0.0-py3-none-any.whl (243 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.2/243.2 kB 13.7 MB/s eta 0:00:00[2025-07-09 08:21:22.632434] 
Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 118.9 MB/s eta 0:00:00[2025-07-09 08:21:22.646063] 
Downloading pygments-2.19.2-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 91.7 MB/s eta 0:00:00[2025-07-09 08:21:22.671799] 
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pygments, mdurl, markdown-it-py, rich
  Attempting uninstall: pygments
    Found existing installation: Pygments 2.19.2
    Uninstalling Pygments-2.19.2:
      Successfully uninstalled Pygments-2.19.2
  Attempting uninstall: mdurl
    Found existing installation: mdurl 0.1.2
    Uninstalling mdurl-0.1.2:
      Successfully uninstalled mdurl-0.1.2
  Attempting uninstall: markdown-it-py
    Found existing installation: markdown-it-py 3.0.0
    Uninstalling markdown-it-py-3.0.0:
      Successfully uninstalled markdown-it-py-3.0.0
  Attempting uninstall: rich
    Found existing installation: rich 14.0.0
    Uninstalling rich-14.0.0:
      Successfully uninstalled rich-14.0.0
Successfully installed markdown-it-py-3.0.0 mdurl-0.1.2 pygments-2.19.2 rich-14.0.0

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: pip install --upgrade pip

────────────────────────────────────────────────────────────────────────────────────────

[08:21:24] ❗️ installer returned a non-zero exit code
[08:21:24] ❗️ Error during processing dependencies! Please fix the error and push an update, or try restarting the app.